###
http://redstar002.iptime.org:20310/rest/exec?cmd=pwd  

### gpu 온도 
http://redstar002.iptime.org:20310/rest/exec?cmd=/opt/vc/bin/vcgencmd%20measure_temp  

### cpu 온도 
http://localhost:20310/rest/exec?cmd=cat%20/sys/class/thermal/thermal_zone0/temp
